# Generated by Django 5.0.3 on 2024-04-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productnumberphone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgender',
            options={'managed': True, 'verbose_name': 'Género producto', 'verbose_name_plural': 'ProductGenders'},
        ),
        migrations.AlterModelOptions(
            name='productnumberphone',
            options={'managed': True, 'verbose_name': 'Telefono producto', 'verbose_name_plural': 'product_number_phone'},
        ),
    ]
